env:
  browser: true
  node: true
  es6: true
extends:
  - airbnb-typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
ignorePatterns:
  - "**/*.d.ts"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".tsx"
        - ".jsx"
  import/no-unresolved: off
  import/extensions: off
  react/jsx-props-no-spreading: off
  no-shadow: warn
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/*.test.ts"
        - "**/*.test.tsx"
        - "**/*.spec.ts"
        - "**/*.spec.tsx"
        - "**/*.stories.ts"
        - "**/*.stories.tsx"
